name = "sparkle_vhdl"

[language]
vhdl.standard = "2008"

[rtl]
sources = [
    "vhdl/util_pkg.vhdl",
    "vhdl/sipo.vhdl",
    "vhdl/piso.vhdl",
    "vhdl/sparkle.vhdl",
    "vhdl/design_pkg.vhd",
    "vhdl/LWC_config.vhd",
    "vhdl/LWC/NIST_LWAPI_pkg.vhd",
    "vhdl/cryptocore.vhd",
    "vhdl/LWC/data_sipo.vhd",
    "vhdl/LWC/key_piso.vhd",
    "vhdl/LWC/data_piso.vhd",
    "vhdl/LWC/PreProcessor.vhd",
    "vhdl/LWC/PostProcessor.vhd",
    "vhdl/LWC/fifo.vhd",
    "vhdl/LWC/LWC.vhd",
]
top = "LWC"
clock_port = "clk"

[tb]
sources = ["tb/LWC_TB.vhd"]
top = "LWC_TB"

generics.G_FNAME_PDI.file = "KAT/kats_for_verification/pdi.txt"
generics.G_FNAME_SDI.file = "KAT/kats_for_verification/sdi.txt"
generics.G_FNAME_DO.file = "KAT/kats_for_verification/do.txt"
generics.G_TEST_MODE = 1                                       # 1: stall both inputs and output, 4: timing measurement
generics.G_RANDOM_STALL = true
generics.G_MAX_FAILURES = 0
generics.G_TIMEOUT_CYCLES = 100
generics.G_VERBOSE_LEVEL = 0
generics.G_PDI_STALLS = 3
generics.G_SDI_STALLS = 5
generics.G_DO_STALLS = 7
